require 'user.options'
require 'user.keymaps'
require 'user.plugins'

-- Plugins config in deep
require 'user.colorschemes'
require 'user.cmp'
require 'user.lsp'
require 'user.telescope'
require 'user.treesitter'
require 'user.autopairs'
require 'user.comments'
require 'user.gitsigns'
require 'user.nvim-tree'
require 'user.bufferline'
require 'user.lualine'
require 'user.toggleterm'
require 'user.impatient'
require 'user.indentline'
require 'user.alpha'
require 'user.whichkey'
require 'user.autocommands'
